name: dapy
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn=0.23.2
  - nodejs
  - ipywidgets
  - widgetsnbextension
  - jupyter_contrib_nbextensions
  - jupyterlab
  - rise
