name: dapy
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - nodejs
  - ipywidgets
  - widgetsnbextensions
  - jupyter_contrib_nbextensions
  - jupyterlab
  - rise